/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    'greeting': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'greeting'?: string;
  }

  interface OtherComponent {
    'greeting': string;
  }
  interface OtherComponentAttributes extends StencilHTMLAttributes {
    'greeting'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'OtherComponent': Components.OtherComponent;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'other-component': Components.OtherComponentAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLOtherComponentElement extends Components.OtherComponent, HTMLStencilElement {}
  var HTMLOtherComponentElement: {
    prototype: HTMLOtherComponentElement;
    new (): HTMLOtherComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'other-component': HTMLOtherComponentElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'other-component': HTMLOtherComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
